# Generated by Django 3.2.9 on 2021-11-23 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField()),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=1)),
                ('qtd_turmas', models.IntegerField()),
                ('qtd_alunos_por_turma', models.IntegerField()),
                ('disciplinas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ano_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='escola.ano')),
                ('id_aluno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('rg_cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('matricula', models.IntegerField(unique=True)),
                ('nomeMae', models.CharField(max_length=255)),
                ('nomePai', models.CharField(max_length=255)),
                ('desblocado', models.BooleanField(default=False)),
                ('nascimento', models.DateField()),
                ('ingresso', models.DateField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmaAluno', to='escola.ano')),
            ],
            bases=('escola.ano',),
        ),
    ]
