# Generated by Django 3.2.9 on 2021-11-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='ano_ptr',
        ),
    ]
